name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - run: echo '${{ steps.stepid.outputs.dotnet-version }}'
 
    - name: dotnet build
      run: dotnet build ContosoUniversity.sln -c Release
      
    - name: Start Docker for sql
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=sqlPw3$secure' -e 'MSSQL_PID=Developer' -p 1433:1433 --name msssql -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu

    - name: dotnet test
      env:
        ConnectionStrings:SchoolContext: Server=localhost;User Id=sa;Password=sqlPw3$secure;TrustServerCertificate=True;
      run: dotnet test ContosoUniversity.sln -c Release --no-build