name: CI

on: [push, pull_request]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sqlPw3$secure

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: dotnet build
      run: dotnet build -c Release

    - name: dotnet test
      run: dotnet test -c Release --no-build
      env:
        ConnectionStrings__SchoolContext: Server=.;Database=ContosoUniversity-Tests;User=sa;Password=sqlPw3$secure;TrustServerCertificate=True;Encrypt=false;
